### ISSUE TITLE
How to fix this code?

### ISSUE THREAD

**Issue by 486xtm** [486xtm/React-Sign#5]
updateCharacterType: async (req: Request, res: Response) => {
    try{
      const {characterType} = req.body;
      await Users.findOneAndUpdate({_id: req.params.id},
        {
          characterType
        }
      );
      res.json({msg: "Update CharacterType Success!"})
    } catch (err: any) {
      return res.status(533).json({msg: err.message});
    }
  },

**Comment by eyovvalupe** [comment]
updateCharacterType: async (req: Request, res: Response) => {
try{
const {characterType} = req.body;
await Users.findOneAndUpdate({_id: req.params.id},
{
characterType
}
);
res.json({msg: "Update CharacterType Success!"})
} catch (err: any) {
return res.status(501).json({msg: err.message});
}
},

**Comment by 486xtm** [comment]
> updateCharacterType: async (req: Request, res: Response) => { try{ const {characterType} = req.body; await Users.findOneAndUpdate({_id: req.params.id}, { characterType } ); res.json({msg: "Update CharacterType Success!"}) } catch (err: any) { return res.status(501).json({msg: err.message}); } },

it works well.. thx
